<?php
// Central product dataset used across pages
$products = [
  [
    'id' => 1,
    'title' => 'Ebook: Mastering HTML Templates',
    'slug' => 'mastering-html-templates',
    'description' => 'A comprehensive guide to building and customizing HTML templates.',
    'category' => 'Ebooks',
    'price' => 19,
    'image' => 'https://picsum.photos/seed/dpm-101/1200/800',
    'thumb' => 'https://picsum.photos/seed/dpm-101/600/600',
    'tags' => ['ebooks', 'html', 'templates'],
    'rating' => 4.8,
    'sales' => 860,
    'created_at' => '2024-04-05',
    'author' => ['name' => 'Jane Creator', 'avatar' => 'https://i.pravatar.cc/64?img=1'],
  ],
  [
    'id' => 2,
    'title' => 'Course: Tailwind CSS From Zero to Pro',
    'slug' => 'tailwind-css-zero-to-pro',
    'description' => 'Learn Tailwind by building real-world components and layouts.',
    'category' => 'Courses',
    'price' => 49,
    'image' => 'https://picsum.photos/seed/dpm-102/1200/800',
    'thumb' => 'https://picsum.photos/seed/dpm-102/600/600',
    'tags' => ['courses', 'tailwindcss', 'frontend'],
    'rating' => 4.9,
    'sales' => 1240,
    'created_at' => '2024-06-10',
    'author' => ['name' => 'Alex Dev', 'avatar' => 'https://i.pravatar.cc/64?img=2'],
  ],
  [
    'id' => 3,
    'title' => 'SaaS Starter: License Manager (PHP)',
    'slug' => 'saas-starter-license-manager-php',
    'description' => 'Starter boilerplate to manage licenses, updates, and subscriptions.',
    'category' => 'Software',
    'price' => 79,
    'image' => 'https://picsum.photos/seed/dpm-103/1200/800',
    'thumb' => 'https://picsum.photos/seed/dpm-103/600/600',
    'tags' => ['software', 'php', 'saas'],
    'rating' => 4.7,
    'sales' => 520,
    'created_at' => '2024-07-01',
    'author' => ['name' => 'Code Forge', 'avatar' => 'https://i.pravatar.cc/64?img=3'],
  ],
  [
    'id' => 4,
    'title' => 'Ebook: SEO for Digital Sellers',
    'slug' => 'seo-for-digital-sellers',
    'description' => 'Increase organic traffic using up-to-date SEO techniques.',
    'category' => 'Ebooks',
    'price' => 15,
    'image' => 'https://picsum.photos/seed/dpm-104/1200/800',
    'thumb' => 'https://picsum.photos/seed/dpm-104/600/600',
    'tags' => ['ebooks', 'seo', 'marketing'],
    'rating' => 4.6,
    'sales' => 690,
    'created_at' => '2024-03-12',
    'author' => ['name' => 'Priya M', 'avatar' => 'https://i.pravatar.cc/64?img=4'],
  ],
  [
    'id' => 5,
    'title' => 'Course: JavaScript Patterns',
    'slug' => 'javascript-patterns',
    'description' => 'Master reusable patterns and architecture in JS apps.',
    'category' => 'Courses',
    'price' => 39,
    'image' => 'https://picsum.photos/seed/dpm-105/1200/800',
    'thumb' => 'https://picsum.photos/seed/dpm-105/600/600',
    'tags' => ['courses', 'javascript', 'architecture'],
    'rating' => 4.8,
    'sales' => 980,
    'created_at' => '2024-02-22',
    'author' => ['name' => 'Sam JS', 'avatar' => 'https://i.pravatar.cc/64?img=5'],
  ],
  [
    'id' => 6,
    'title' => 'UI Kit: Landing Page Components',
    'slug' => 'ui-kit-landing-components',
    'description' => 'A set of modern, responsive components for landing pages.',
    'category' => 'Software',
    'price' => 29,
    'image' => 'https://picsum.photos/seed/dpm-106/1200/800',
    'thumb' => 'https://picsum.photos/seed/dpm-106/600/600',
    'tags' => ['software', 'ui', 'components'],
    'rating' => 4.5,
    'sales' => 450,
    'created_at' => '2024-05-18',
    'author' => ['name' => 'Design Hub', 'avatar' => 'https://i.pravatar.cc/64?img=6'],
  ],
  [
    'id' => 7,
    'title' => 'Course: PHP & MySQL Crash Course',
    'slug' => 'php-mysql-crash-course',
    'description' => 'Fast-paced course to build CRUD apps with PHP & MySQL.',
    'category' => 'Courses',
    'price' => 35,
    'image' => 'https://picsum.photos/seed/dpm-107/1200/800',
    'thumb' => 'https://picsum.photos/seed/dpm-107/600/600',
    'tags' => ['courses', 'php', 'mysql'],
    'rating' => 4.7,
    'sales' => 770,
    'created_at' => '2024-01-20',
    'author' => ['name' => 'DB Pro', 'avatar' => 'https://i.pravatar.cc/64?img=7'],
  ],
  [
    'id' => 8,
    'title' => 'Template: Blog + Docs',
    'slug' => 'template-blog-docs',
    'description' => 'Clean blog and documentation template with MDX-ready layout.',
    'category' => 'Software',
    'price' => 24,
    'image' => 'https://picsum.photos/seed/dpm-108/1200/800',
    'thumb' => 'https://picsum.photos/seed/dpm-108/600/600',
    'tags' => ['software', 'template', 'docs'],
    'rating' => 4.4,
    'sales' => 390,
    'created_at' => '2024-03-01',
    'author' => ['name' => 'Docu Lab', 'avatar' => 'https://i.pravatar.cc/64?img=8'],
  ],
  [
    'id' => 9,
    'title' => 'Ebook: Monetize Digital Products',
    'slug' => 'monetize-digital-products',
    'description' => 'Proven strategies to monetize and scale digital products.',
    'category' => 'Ebooks',
    'price' => 22,
    'image' => 'https://picsum.photos/seed/dpm-109/1200/800',
    'thumb' => 'https://picsum.photos/seed/dpm-109/600/600',
    'tags' => ['ebooks', 'business', 'marketing'],
    'rating' => 4.6,
    'sales' => 610,
    'created_at' => '2024-04-20',
    'author' => ['name' => 'Growth Co', 'avatar' => 'https://i.pravatar.cc/64?img=9'],
  ],
  [
    'id' => 10,
    'title' => 'Course: AOS & Animations for UI',
    'slug' => 'aos-animations-ui',
    'description' => 'Animate interfaces using AOS and native CSS transitions.',
    'category' => 'Courses',
    'price' => 29,
    'image' => 'https://picsum.photos/seed/dpm-110/1200/800',
    'thumb' => 'https://picsum.photos/seed/dpm-110/600/600',
    'tags' => ['courses', 'aos', 'animations'],
    'rating' => 4.5,
    'sales' => 540,
    'created_at' => '2024-07-12',
    'author' => ['name' => 'Motion Lab', 'avatar' => 'https://i.pravatar.cc/64?img=10'],
  ],
  [
    'id' => 11,
    'title' => 'Template: Startup Landing',
    'slug' => 'template-startup-landing',
    'description' => 'High-converting landing page template for startups.',
    'category' => 'Software',
    'price' => 32,
    'image' => 'https://picsum.photos/seed/dpm-111/1200/800',
    'thumb' => 'https://picsum.photos/seed/dpm-111/600/600',
    'tags' => ['software', 'landing', 'startup'],
    'rating' => 4.7,
    'sales' => 830,
    'created_at' => '2024-06-01',
    'author' => ['name' => 'Launch Kit', 'avatar' => 'https://i.pravatar.cc/64?img=11'],
  ],
  [
    'id' => 12,
    'title' => 'Ebook: Design Systems Handbook',
    'slug' => 'design-systems-handbook',
    'description' => 'Build and maintain design systems for teams of any size.',
    'category' => 'Ebooks',
    'price' => 26,
    'image' => 'https://picsum.photos/seed/dpm-112/1200/800',
    'thumb' => 'https://picsum.photos/seed/dpm-112/600/600',
    'tags' => ['ebooks', 'design', 'systems'],
    'rating' => 4.9,
    'sales' => 1120,
    'created_at' => '2024-08-15',
    'author' => ['name' => 'UX Studio', 'avatar' => 'https://i.pravatar.cc/64?img=12'],
  ],
];


